on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install dependencies
      run: go get .
    - name: Run Tests
      run: go test -json ./... > TestResults-${{ matrix.platform }}-${{ matrix.go-version }}.json
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.platform }}-${{ matrix.go-version }}
        path: TestResults-${{ matrix.platform }}-${{ matrix.go-version }}.json